# Generated by Django 5.0.7 on 2024-07-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auths", "0004_remove_mutsauser_age_remove_mutsauser_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mutsauser",
            name="mail",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name="mutsauser",
            name="refresh_token",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name="mutsauser",
            name="user_name",
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
