# Generated by Django 5.0.7 on 2024-07-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auths", "0005_mutsauser_mail_mutsauser_refresh_token_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mutsauser",
            name="mail",
        ),
        migrations.AddField(
            model_name="mutsauser",
            name="email",
            field=models.EmailField(blank=True, max_length=1024),
        ),
    ]
