# Generated by Django 5.0.7 on 2024-07-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auths", "0006_remove_mutsauser_mail_mutsauser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mutsauser",
            name="school",
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
