# Generated by Django 5.0.7 on 2024-07-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auths", "0007_alter_mutsauser_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="mutsauser",
            name="college",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name="mutsauser",
            name="profile",
            field=models.ImageField(blank=True, upload_to="profiles/"),
        ),
    ]
