# Generated by Django 5.0.7 on 2024-07-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0008_mutsauser_college_mutsauser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutsauser',
            name='college',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='mutsauser',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mutsauser',
            name='nickname',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='mutsauser',
            name='school',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='mutsauser',
            name='user_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
