# Generated by Django 5.0.7 on 2024-07-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0009_alter_mutsauser_college_alter_mutsauser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutsauser',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
