# Generated by Django 5.0.7 on 2024-07-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0010_alter_mutsauser_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutsauser',
            name='college',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='mutsauser',
            name='email',
            field=models.EmailField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='mutsauser',
            name='nickname',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='mutsauser',
            name='profile',
            field=models.CharField(blank=True, choices=[('gentle', 'gentle'), ('serious', 'serious'), ('sharp', 'sharp')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mutsauser',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='mutsauser',
            name='school',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='mutsauser',
            name='user_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterModelTable(
            name='mutsauser',
            table='mutsa_user',
        ),
    ]
