# Generated by Django 5.0.7 on 2024-07-25 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("verify", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="verify",
            old_name="user",
            new_name="userId",
        ),
    ]
