# Generated by Django 5.0.7 on 2024-07-25 16:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("verify", "0002_rename_user_verify_userid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="verify",
            old_name="userId",
            new_name="user",
        ),
    ]
