# Generated by Django 5.0.7 on 2024-08-01 00:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("timer", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="timer",
            old_name="end_time",
            new_name="rest_time",
        ),
    ]
