# Generated by Django 5.0.7 on 2024-08-01 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timer", "0002_rename_end_time_timer_rest_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timer",
            name="duration",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
