# Generated by Django 5.0.7 on 2024-08-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timer", "0003_alter_timer_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timer",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
