# Generated by Django 5.0.7 on 2024-08-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timer", "0004_alter_timer_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="timer",
            name="rest_status",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
